config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'

  get 'greeter/hello' => "greeter#hello"
  get 'greeter/goodbye'

  root 'courses#index'

end

app/models/coursera.rb
class Coursera
	include HTTParty

	default_options.update(verify: false)
	base_uri 'https://api.coursera.org/api/catalog.v1/courses'
	default_params fields: "smallIcon,shortDescription", q: "search"
	format :json

	def self.for term
		get("", query: { query: term}) ["elements"]
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
  	@search_team = params[:looking_for] || 'jhu'
  	@courses = Coursera.for(@search_team)
  end
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
  	random_names = ["Alex","Joe","Michael"]
  	@name = random_names.sample
  	@time = Time.now
  	@times_displayed ||= 0
  	@times_displayed += 1
  end
  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
	def formatted_time (time)
		# time string in AM/PM format
		time.strftime("%I:%M%p")
	end
end

app/views/courses/index.html.erb
<h1>Searching for - <%= @search_team %></h1>
<table border="1">
	<tr>
		<th>Image</th>
		<th>Name</th>
		<th>Description</th>
	</tr>
	<% @courses.each do |course| %>
		<tr class=<%= cycle('even','odd') %>>
			<td><%= image_tag(course["smallIcon"])%></td>
			<td><%= course["name"] %></td>
			<td><%= course["shortDescription"] %></td>
		</tr>
	<% end %>
</table>

app/views/greeter/goodbye.html.erb
<% random_names = ["Alex","Joe","Michael"] %>
<h1>Goodbye, <%= random_names.sample %> </h1>
<p> The time now is <%= Time.now %></p>

app/views/greeter/hello.html.erb
<h1>Greetings, <%= @name %> </h1>
<p> The time now is <%= formatted_time(@time) %></p>
<p> This page has been viewed <%= @times_displayed %> time(s)</p>
<P><%= link_to "Google", "http://google.com" %></P>
<P><%= link_to "Goodbye", greeter_goodbye_path %></P>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstApplication</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>